DROP SEQUENCE BOARD_SEQ;
DROP TABLE BOARD;

CREATE SEQUENCE BOARD_SEQ START WITH 1
INCREMENT BY 1;

CREATE TABLE BOARD(
   NO 			NUMBER PRIMARY KEY,
   TITLE  		VARCHAR2(100),
   CONTENT  	VARCHAR2(4000),
   ID			VARCHAR2(100),
   REGDATE  	DATE,
   ATTACHMENT	VARCHAR2(255)
);


INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'TITLE1', 'CONTENT-1', 'admin', SYSDATE, NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'TITLE2', 'CONTENT-2', 'admin', SYSDATE, NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'TITLE3', 'CONTENT-3', 'admin', SYSDATE, NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'TITLE4', 'CONTENT-4', 'admin', SYSDATE, NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'TITLE5', 'CONTENT-5', 'admin', SYSDATE, NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'TITLE6', 'CONTENT-6', 'admin', SYSDATE, NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'TITLE7', 'CONTENT-7', 'admin', SYSDATE, NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'TITLE8', 'CONTENT-8', 'admin', SYSDATE, NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'TITLE9', 'CONTENT-9', 'admin', SYSDATE, NULL);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'TITLE10', 'CONTENT-10', 'admin', SYSDATE, NULL);

SELECT * FROM BOARD;